### ISSUE TITLE
No default export after transformation

### ISSUE THREAD

**Issue by aheissenberger** [cyco130/vite-plugin-cjs-interop#31] opened 2024-02-13 20:51 UTC
I still get the the error for some imports after transformation in the browser.
Any idea on how I can debug this?

**ERROR in Browser Console:**
```
react-server-dom-webpack_client.js?v=18063975:866 Uncaught SyntaxError: The requested module '/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/isNumber.js?v=c30a9c6d' does not provide an export named 'default' (at DataUtils.js?v=c30a9c6d:8:8)
```

**`vite.config.ts`**
```ts
import { defineConfig } from 'vite';
import { cjsInterop } from 'vite-plugin-cjs-interop';

export default defineConfig(({ mode }) => ({
  ...({
    optimizeDeps: {
      include: ['dayjs','dayjs/**/*'],
      exclude: ['@mantine/core','@mantine/hooks'],
    },
    ssr: {
      noExternal: ['@mantine/core','@mantine/hooks'],
    },
  }),
  plugins: [
    cjsInterop({
      // List of CJS dependencies that require interop
      dependencies: [
      'lodash/**/*',
    ],
      client: true,
      apply:'serve'
    }),
  ],
}));
```

**`DataUtils.js?v=c30a9c6d:8:8`:**
```js
const {default: isString=__cjsInterop4__} = __cjsInterop4__?.default?.__esModule ? __cjsInterop4__.default : __cjsInterop4__;
const {default: isNan=__cjsInterop3__} = __cjsInterop3__?.default?.__esModule ? __cjsInterop3__.default : __cjsInterop3__;
const {default: get=__cjsInterop2__} = __cjsInterop2__?.default?.__esModule ? __cjsInterop2__.default : __cjsInterop2__;
const {default: lodashIsNumber=__cjsInterop1__} = __cjsInterop1__?.default?.__esModule ? __cjsInterop1__.default : __cjsInterop1__;
import __cjsInterop4__ from "/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/isString.js?v=3e84beda";
import __cjsInterop3__ from "/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/isNaN.js?v=3e84beda";
import __cjsInterop2__ from "/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/get.js?v=3e84beda";
import /* Line:8, Character: 8 */__cjsInterop1__ from "/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/isNumber.js?v=3e84beda";
export var mathSign = function mathSign(value) {
    if (value === 0) {
        return 0;
    }
    if (value > 0) {
        return 1;
    }
    return -1;
};
...
```

This is are some console.log values from the cjs plugin:
* the `cjs-interop-msg` document the parameter `id` and the first 10 characters of `code`
* the `cjs-interop-fix-id` is the `node.source.value` before pushed to `toBeFixed`
```
cjs-interop-msg /Users/ah/SVN-Checkouts/TST/waku-mantine/node_modules/.pnpm/@mantine+dates@7.5.2_@mantine+core@7.5.2_@mantine+hooks@7.5.2_dayjs@1.11.10_react-dom@18.3.0-_ijs54lfvbjpc5kq3mttqn75pb4/node_modules/@mantine/dates/styles.css CODE: "export def"
cjs-interop-msg /Users/ah/SVN-Checkouts/TST/waku-mantine/node_modules/.pnpm/@mantine+dates@7.5.2_@mantine+core@7.5.2_@mantine+hooks@7.5.2_dayjs@1.11.10_react-dom@18.3.0-_ijs54lfvbjpc5kq3mttqn75pb4/node_modules/@mantine/dates/styles.css CODE: "import { u"
cjs-interop-msg /Users/ah/SVN-Checkouts/TST/waku-mantine/node_modules/.pnpm/@mantine+dates@7.5.2_@mantine+core@7.5.2_@mantine+hooks@7.5.2_dayjs@1.11.10_react-dom@18.3.0-_ijs54lfvbjpc5kq3mttqn75pb4/node_modules/@mantine/dates/styles.css CODE: "export def"
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/sortBy
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/throttle
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isObject
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isObject
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/last
cjs-interop-fix-id lodash/upperFirst
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/upperFirst
cjs-interop-fix-id lodash/maxBy
cjs-interop-fix-id lodash/minBy
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/last
cjs-interop-fix-id lodash/first
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/range
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/some
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/max
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isNaN
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/maxBy
cjs-interop-fix-id lodash/min
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/sumBy
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isNumber
cjs-interop-fix-id lodash/isString
cjs-interop-fix-id lodash/omit
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/isNaN
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/omit
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isString
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isObject
cjs-interop-fix-id lodash/uniqBy
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isString
cjs-interop-fix-id lodash/isNaN
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/isNumber
cjs-interop-fix-id lodash/isObject
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/max
cjs-interop-fix-id lodash/min
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isString
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/flatMap
cjs-interop-fix-id lodash/isNaN
cjs-interop-fix-id lodash/upperFirst
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/sortBy
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isPlainObject
cjs-interop-fix-id lodash/isBoolean
cjs-interop-fix-id lodash/isEqual
cjs-interop-fix-id lodash/mapValues
cjs-interop-fix-id lodash/every
cjs-interop-fix-id lodash/find
cjs-interop-fix-id lodash/every
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/isNil
cjs-interop-fix-id lodash/isFunction
cjs-interop-fix-id lodash/range
cjs-interop-fix-id lodash/get
cjs-interop-fix-id lodash/sortBy
cjs-interop-fix-id lodash/throttle
cjs-interop-fix-id lodash/memoize
```

**Comment by cyco130** [comment] 2024-02-14 17:07
Is it possible for you to provide a small repro?

**Comment by cyco130** [comment] 2024-03-27 07:58
Closing because of lack of reproduction.

**Closed by cyco130** 2024-03-27 07:58 UTC
